// Generated by Melange
'use strict';

var Seq = require("bs-platform/lib/js/seq.js");

var empty = Seq.empty;

var $$return = Seq.$$return;

var cons = Seq.cons;

var append = Seq.append;

var map = Seq.map;

var filter = Seq.filter;

var filter_map = Seq.filter_map;

var flat_map = Seq.flat_map;

var fold_left = Seq.fold_left;

var iter = Seq.iter;

var unfold = Seq.unfold;

exports.empty = empty;
exports.$$return = $$return;
exports.cons = cons;
exports.append = append;
exports.map = map;
exports.filter = filter;
exports.filter_map = filter_map;
exports.flat_map = flat_map;
exports.fold_left = fold_left;
exports.iter = iter;
exports.unfold = unfold;
/* No side effect */
